version: '2'
routify:
  sapper:
    image: aamservices/pm2-routify:latest
    restart: unless-stopped
    volumes:
      - data:/usr/src/app
    networks:
      - internal
    ports:
      - 3000
volumes:
  data:
    driver: local
